# Generated by Django 5.1.15 on 2026-09-11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0062_annotation_status_annotation_version_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assignee',
            field=models.ForeignKey(
                blank=True,
                db_index=True,
                help_text='Labeler this task is assigned to. Null means unassigned.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='assigned_tasks',
                to=settings.AUTH_USER_MODEL,
                verbose_name='assignee',
            ),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='assigned at'),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_by',
            field=models.ForeignKey(
                blank=True,
                help_text='User who most recently assigned this task.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='tasks_assigned_by',
                to=settings.AUTH_USER_MODEL,
                verbose_name='assigned by',
            ),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'assignee'], name='task_project_assignee_idx'),
        ),
    ]
